spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    generate-ddl: true

heroku:
  frontend:
    url: ${FRONTEND_URL}

cors:
  originPatterns: ${CORS_ORIGINS}

cookie:
  lifetime: ${COOKIE_LENGTH}

aws:
  region: ${AWS_REGION}
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  bucketName: ${AWS_BUCKET_NAME}