spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    generate-ddl: true

heroku:
  frontend:
    url: ${FRONTEND_URL}

itsc:
  tenantId: ${ITSC_TENANT_ID}
  clientId: ${ITSC_CLIENT_ID}
  clientSecret: ${ITSC_CLIENT_SECRET}

cors:
  originPatterns: ${CORS_ORIGINS}