# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: SpringBoot CI Test
    runs-on: ubuntu-latest

    steps:
    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v3
    
    # Run gradle test
    - name: Run gradle test
      run: |
        chmod +x gradlew
        ./gradlew test
