name: springboot-docker-heroku CD

on:
  push:
    branches: [ master ]

#set environment variables
env:
  HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Build application jar
      - name: Build application jar
        run: |
          chmod +x gradlew
          ./gradlew bootJar

      # Build Docker image
      - name: Docker build
        run: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
